name: arfilming
description: Arfilming Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Network
  http:
  connectivity_plus: 

  # State management
  flutter_bloc: 
  bloc_concurrency: 
  equatable: 

  # Local Storage
  flutter_secure_storage: 

  # Local notifications
  # flutter_local_notifications: 

  # Services
  intl: 
  get_it: 
  uni_links: 
  device_info_plus: 
  url_launcher: 
  share_extend: 

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: 
  flutter_screenutil: 
  cached_network_image: 

  # Assets, fonts, colors generator
  flutter_gen: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Launcher Icon
  # flutter pub run flutter_launcher_icons --file flutter_launcher_icons.yaml
  flutter_launcher_icons: 

  # Runners
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  build_runner: 
  flutter_gen_runner: 
  
  # Linter
  flutter_lints: ^2.0.0


flutter:
  # generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/colors/colors.xml

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf
        - asset: assets/fonts/raleway/Raleway-ExtraLight.ttf
        - asset: assets/fonts/raleway/Raleway-Light.ttf
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: assets/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/src/core/l10n/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false

  localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/flutter-localization-workflow
    project_id: # Configured manually or through 'Connect to Localizely' command. Get it from the https://app.localizely.com/projects page.
    branch: # Configured manually. Get it from the “Branches” page on the Localizely platform, in case branching is enabled and you want to use a non-main branch.
    upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
    upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
    upload_tag_added: # Optional list of tags to add to new translations with upload (e.g. ['new', 'New translation']). Default: []
    upload_tag_updated: # Optional list of tags to add to updated translations with upload (e.g. ['updated', 'Updated translation']). Default: []
    upload_tag_removed: # Optional list of tags to add to removed translations with upload (e.g. ['removed', 'Removed translation']). Default: []
    download_empty_as: # Set to empty|main|skip, to configure how empty translations should be exported from the Localizely platform. Default: empty
    download_include_tags: # Optional list of tags to be downloaded (e.g. ['include', 'Include key']). If not set, all string keys will be considered for download. Default: []
    download_exclude_tags: # Optional list of tags to be excluded from download (e.g. ['exclude', 'Exclude key']). If not set, all string keys will be considered for download. Default: []
    ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false


flutter_gen:
  output: lib/src/core/flutter_gen/generated/
  line_length: 80   # Optional (default: 80)

  integrations:
    flutter_svg: true
    rive: true

  assets:
    enabled: true
    package_parameter_enabled: false
    # Assets.imagesChip
    # style: camel-case

    # Assets.images_chip
    # style: snake-case

    # Assets.images.chip (default style)
    # style: dot-delimiter
    outputs:
      class_name: AppAssets

  fonts:
    enabled: true
    outputs:
      class_name: AppFonts

  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors
